//! Telegram Inline Actions
//!
//! Exposes inline keyboard builder utilities and callback query pipelines.

use anyhow::Result;
use tracing::info;

pub struct TelegramInline;

impl TelegramInline {
    /// Builds an Inline Keyboard block for user decisions (e.g., Yes/No config prompts)
    pub fn build_confirmation_keyboard() -> String {
        // MOCK: JSON payload representing `InlineKeyboardMarkup`
        r#"{"inline_keyboard": [[{"text": "Yes", "callback_data": "confirm_yes"}, {"text": "No", "callback_data": "confirm_no"}]]}"#.into()
    }

    /// Processes a callback query generated by a user clicking an inline button.
    pub async fn handle_callback_query(callback_id: &str, data: &str, user_id: i64) -> Result<()> {
        info!("Processing callback query {} from {}: {}", callback_id, user_id, data);
        
        // Return Ok instantly so to clear the client loading spinner
        Ok(())
    }
}
